version: '3.9'

services:

  project_service:
    container_name: project_service
    build: ./
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - GLhost

  migrate:
    image: migrate/migrate
    networks:
      - GLhost
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations", 
      "-database", "postgres://postgres:1234@postgres-db:5432/project_control?sslmode=disable", 
      "up"
    ]
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: project_control
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: project_control
    volumes:
      - db:/project-database/project-memory
    ports:
      - "5434:5434"
    networks:
      - GLhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_control -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:latest"
    container_name: redis_auth
    ports:
      - "6377:6379"
    networks:
      - GLhost

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper_auth
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2218:2181
    networks:
      - GLhost

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka_auth
    depends_on:
      - zookeeper
    ports:
      - 29097:29092
    networks:
      - GLhost
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_auth:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  GLhost:
    driver: bridge
    external: true

volumes:
  db: