// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: submodule/protos/protos/group.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Developer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber      string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	TelegramUsername string `protobuf:"bytes,3,opt,name=telegram_username,json=telegramUsername,proto3" json:"telegram_username,omitempty"`
}

func (x *Developer) Reset() {
	*x = Developer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer) ProtoMessage() {}

func (x *Developer) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer.ProtoReflect.Descriptor instead.
func (*Developer) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{0}
}

func (x *Developer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Developer) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Developer) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

type CreateGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwaggerUrl    string           `protobuf:"bytes,1,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	Name          string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Developers    []*Developer     `protobuf:"bytes,3,rep,name=developers,proto3" json:"developers,omitempty"`
	Documentation []*Documentation `protobuf:"bytes,4,rep,name=documentation,proto3" json:"documentation,omitempty"`
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupReq) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetDevelopers() []*Developer {
	if x != nil {
		return x.Developers
	}
	return nil
}

func (x *CreateGroupReq) GetDocumentation() []*Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

type GroupGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SwaggerUrl    string         `protobuf:"bytes,2,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	Name          string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Developers    *Developer     `protobuf:"bytes,4,opt,name=developers,proto3" json:"developers,omitempty"`
	Documentation *Documentation `protobuf:"bytes,5,opt,name=documentation,proto3" json:"documentation,omitempty"`
	CreatedAt     string         `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GroupGet) Reset() {
	*x = GroupGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupGet) ProtoMessage() {}

func (x *GroupGet) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupGet.ProtoReflect.Descriptor instead.
func (*GroupGet) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupGet) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *GroupGet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupGet) GetDevelopers() *Developer {
	if x != nil {
		return x.Developers
	}
	return nil
}

func (x *GroupGet) GetDocumentation() *Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

func (x *GroupGet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateGr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body *BodyUptd `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *UpdateGr) Reset() {
	*x = UpdateGr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGr) ProtoMessage() {}

func (x *UpdateGr) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGr.ProtoReflect.Descriptor instead.
func (*UpdateGr) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGr) GetBody() *BodyUptd {
	if x != nil {
		return x.Body
	}
	return nil
}

type BodyUptd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwaggerUrl    string           `protobuf:"bytes,1,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	Name          string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Developers    []*Developer     `protobuf:"bytes,3,rep,name=developers,proto3" json:"developers,omitempty"`
	Documentation []*Documentation `protobuf:"bytes,4,rep,name=documentation,proto3" json:"documentation,omitempty"`
}

func (x *BodyUptd) Reset() {
	*x = BodyUptd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyUptd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyUptd) ProtoMessage() {}

func (x *BodyUptd) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyUptd.ProtoReflect.Descriptor instead.
func (*BodyUptd) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{4}
}

func (x *BodyUptd) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *BodyUptd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BodyUptd) GetDevelopers() []*Developer {
	if x != nil {
		return x.Developers
	}
	return nil
}

func (x *BodyUptd) GetDocumentation() []*Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

type DeleteGr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGr) Reset() {
	*x = DeleteGr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGr) ProtoMessage() {}

func (x *DeleteGr) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGr.ProtoReflect.Descriptor instead.
func (*DeleteGr) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GroupListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *GroupListReq) Reset() {
	*x = GroupListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListReq) ProtoMessage() {}

func (x *GroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListReq.ProtoReflect.Descriptor instead.
func (*GroupListReq) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{6}
}

func (x *GroupListReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GroupListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group []*GroupGet `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty"`
}

func (x *GroupListRes) Reset() {
	*x = GroupListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListRes) ProtoMessage() {}

func (x *GroupListRes) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListRes.ProtoReflect.Descriptor instead.
func (*GroupListRes) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_group_proto_rawDescGZIP(), []int{7}
}

func (x *GroupListRes) GetGroup() []*GroupGet {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_submodule_protos_protos_group_proto protoreflect.FileDescriptor

var file_submodule_protos_protos_group_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x73, 0x75,
	0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x67,
	0x67, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x52, 0x0a, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x0d,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xdb, 0x01, 0x0a, 0x08, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x52,
	0x0a, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x3f, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x55, 0x70, 0x74,
	0x64, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xac, 0x01, 0x0a, 0x08, 0x42, 0x6f, 0x64, 0x79,
	0x55, 0x70, 0x74, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x52, 0x0a,
	0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x41, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x31, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x47, 0x65, 0x74, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x32, 0x87, 0x02, 0x0a,
	0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x22, 0x00, 0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x65, 0x74, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submodule_protos_protos_group_proto_rawDescOnce sync.Once
	file_submodule_protos_protos_group_proto_rawDescData = file_submodule_protos_protos_group_proto_rawDesc
)

func file_submodule_protos_protos_group_proto_rawDescGZIP() []byte {
	file_submodule_protos_protos_group_proto_rawDescOnce.Do(func() {
		file_submodule_protos_protos_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_protos_protos_group_proto_rawDescData)
	})
	return file_submodule_protos_protos_group_proto_rawDescData
}

var file_submodule_protos_protos_group_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_submodule_protos_protos_group_proto_goTypes = []any{
	(*Developer)(nil),      // 0: proto.Developer
	(*CreateGroupReq)(nil), // 1: proto.CreateGroupReq
	(*GroupGet)(nil),       // 2: proto.GroupGet
	(*UpdateGr)(nil),       // 3: proto.UpdateGr
	(*BodyUptd)(nil),       // 4: proto.BodyUptd
	(*DeleteGr)(nil),       // 5: proto.DeleteGr
	(*GroupListReq)(nil),   // 6: proto.GroupListReq
	(*GroupListRes)(nil),   // 7: proto.GroupListRes
	(*Documentation)(nil),  // 8: proto.Documentation
	(*Pagination)(nil),     // 9: proto.Pagination
	(*ById)(nil),           // 10: proto.ById
	(*Void)(nil),           // 11: proto.Void
}
var file_submodule_protos_protos_group_proto_depIdxs = []int32{
	0,  // 0: proto.CreateGroupReq.developers:type_name -> proto.Developer
	8,  // 1: proto.CreateGroupReq.documentation:type_name -> proto.Documentation
	0,  // 2: proto.GroupGet.developers:type_name -> proto.Developer
	8,  // 3: proto.GroupGet.documentation:type_name -> proto.Documentation
	4,  // 4: proto.UpdateGr.Body:type_name -> proto.BodyUptd
	0,  // 5: proto.BodyUptd.developers:type_name -> proto.Developer
	8,  // 6: proto.BodyUptd.documentation:type_name -> proto.Documentation
	9,  // 7: proto.GroupListReq.pagination:type_name -> proto.Pagination
	2,  // 8: proto.GroupListRes.group:type_name -> proto.GroupGet
	1,  // 9: proto.GroupService.CreateGroup:input_type -> proto.CreateGroupReq
	10, // 10: proto.GroupService.GetGroup:input_type -> proto.ById
	6,  // 11: proto.GroupService.ListGroups:input_type -> proto.GroupListReq
	3,  // 12: proto.GroupService.UpdateGroup:input_type -> proto.UpdateGr
	5,  // 13: proto.GroupService.DeleteGroup:input_type -> proto.DeleteGr
	11, // 14: proto.GroupService.CreateGroup:output_type -> proto.Void
	2,  // 15: proto.GroupService.GetGroup:output_type -> proto.GroupGet
	7,  // 16: proto.GroupService.ListGroups:output_type -> proto.GroupListRes
	11, // 17: proto.GroupService.UpdateGroup:output_type -> proto.Void
	11, // 18: proto.GroupService.DeleteGroup:output_type -> proto.Void
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_submodule_protos_protos_group_proto_init() }
func file_submodule_protos_protos_group_proto_init() {
	if File_submodule_protos_protos_group_proto != nil {
		return
	}
	file_submodule_protos_protos_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_submodule_protos_protos_group_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Developer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GroupGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BodyUptd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GroupListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_group_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GroupListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_protos_protos_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_protos_protos_group_proto_goTypes,
		DependencyIndexes: file_submodule_protos_protos_group_proto_depIdxs,
		MessageInfos:      file_submodule_protos_protos_group_proto_msgTypes,
	}.Build()
	File_submodule_protos_protos_group_proto = out.File
	file_submodule_protos_protos_group_proto_rawDesc = nil
	file_submodule_protos_protos_group_proto_goTypes = nil
	file_submodule_protos_protos_group_proto_depIdxs = nil
}
