// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: submodule/protos/protos/private.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePrivateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwaggerUrl       string           `protobuf:"bytes,1,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	PhoneNumber      string           `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	TelegramUsername string           `protobuf:"bytes,3,opt,name=telegram_username,json=telegramUsername,proto3" json:"telegram_username,omitempty"`
	Documentation    []*Documentation `protobuf:"bytes,4,rep,name=documentation,proto3" json:"documentation,omitempty"`
}

func (x *CreatePrivateReq) Reset() {
	*x = CreatePrivateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePrivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateReq) ProtoMessage() {}

func (x *CreatePrivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateReq.ProtoReflect.Descriptor instead.
func (*CreatePrivateReq) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePrivateReq) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *CreatePrivateReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreatePrivateReq) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

func (x *CreatePrivateReq) GetDocumentation() []*Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

type PrivateGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SwaggerUrl       string         `protobuf:"bytes,2,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	PhoneNumber      string         `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	TelegramUsername string         `protobuf:"bytes,4,opt,name=telegram_username,json=telegramUsername,proto3" json:"telegram_username,omitempty"`
	Documentation    *Documentation `protobuf:"bytes,5,opt,name=documentation,proto3" json:"documentation,omitempty"`
	CreatedAt        string         `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *PrivateGet) Reset() {
	*x = PrivateGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateGet) ProtoMessage() {}

func (x *PrivateGet) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateGet.ProtoReflect.Descriptor instead.
func (*PrivateGet) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivateGet) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *PrivateGet) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PrivateGet) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

func (x *PrivateGet) GetDocumentation() *Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

func (x *PrivateGet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdatePrivat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body *BodyUpt `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *UpdatePrivat) Reset() {
	*x = UpdatePrivat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePrivat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivat) ProtoMessage() {}

func (x *UpdatePrivat) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivat.ProtoReflect.Descriptor instead.
func (*UpdatePrivat) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePrivat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePrivat) GetBody() *BodyUpt {
	if x != nil {
		return x.Body
	}
	return nil
}

type BodyUpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwaggerUrl       string           `protobuf:"bytes,1,opt,name=swaggerUrl,proto3" json:"swaggerUrl,omitempty"`
	PhoneNumber      string           `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	TelegramUsername string           `protobuf:"bytes,3,opt,name=telegram_username,json=telegramUsername,proto3" json:"telegram_username,omitempty"`
	Documentation    []*Documentation `protobuf:"bytes,4,rep,name=documentation,proto3" json:"documentation,omitempty"`
}

func (x *BodyUpt) Reset() {
	*x = BodyUpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyUpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyUpt) ProtoMessage() {}

func (x *BodyUpt) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyUpt.ProtoReflect.Descriptor instead.
func (*BodyUpt) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{3}
}

func (x *BodyUpt) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

func (x *BodyUpt) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BodyUpt) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

func (x *BodyUpt) GetDocumentation() []*Documentation {
	if x != nil {
		return x.Documentation
	}
	return nil
}

type DeletePrivat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePrivat) Reset() {
	*x = DeletePrivat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePrivat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrivat) ProtoMessage() {}

func (x *DeletePrivat) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrivat.ProtoReflect.Descriptor instead.
func (*DeletePrivat) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePrivat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PrivateListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *PrivateListReq) Reset() {
	*x = PrivateListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateListReq) ProtoMessage() {}

func (x *PrivateListReq) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateListReq.ProtoReflect.Descriptor instead.
func (*PrivateListReq) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{5}
}

func (x *PrivateListReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PrivateListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Private []*PrivateGet `protobuf:"bytes,1,rep,name=private,proto3" json:"private,omitempty"`
}

func (x *PrivateListRes) Reset() {
	*x = PrivateListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_protos_protos_private_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateListRes) ProtoMessage() {}

func (x *PrivateListRes) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_protos_protos_private_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateListRes.ProtoReflect.Descriptor instead.
func (*PrivateListRes) Descriptor() ([]byte, []int) {
	return file_submodule_protos_protos_private_proto_rawDescGZIP(), []int{6}
}

func (x *PrivateListRes) GetPrivate() []*PrivateGet {
	if x != nil {
		return x.Private
	}
	return nil
}

var File_submodule_protos_protos_private_proto protoreflect.FileDescriptor

var file_submodule_protos_protos_private_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24,
	0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61,
	0x67, 0x67, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11,
	0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe7, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x42, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x55, 0x70, 0x74, 0x52, 0x04, 0x42,
	0x6f, 0x64, 0x79, 0x22, 0xb5, 0x01, 0x0a, 0x07, 0x42, 0x6f, 0x64, 0x79, 0x55, 0x70, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x3a, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x3d, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x32,
	0xa3, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submodule_protos_protos_private_proto_rawDescOnce sync.Once
	file_submodule_protos_protos_private_proto_rawDescData = file_submodule_protos_protos_private_proto_rawDesc
)

func file_submodule_protos_protos_private_proto_rawDescGZIP() []byte {
	file_submodule_protos_protos_private_proto_rawDescOnce.Do(func() {
		file_submodule_protos_protos_private_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_protos_protos_private_proto_rawDescData)
	})
	return file_submodule_protos_protos_private_proto_rawDescData
}

var file_submodule_protos_protos_private_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_submodule_protos_protos_private_proto_goTypes = []any{
	(*CreatePrivateReq)(nil), // 0: proto.CreatePrivateReq
	(*PrivateGet)(nil),       // 1: proto.PrivateGet
	(*UpdatePrivat)(nil),     // 2: proto.UpdatePrivat
	(*BodyUpt)(nil),          // 3: proto.BodyUpt
	(*DeletePrivat)(nil),     // 4: proto.DeletePrivat
	(*PrivateListReq)(nil),   // 5: proto.PrivateListReq
	(*PrivateListRes)(nil),   // 6: proto.PrivateListRes
	(*Documentation)(nil),    // 7: proto.Documentation
	(*Pagination)(nil),       // 8: proto.Pagination
	(*ById)(nil),             // 9: proto.ById
	(*Void)(nil),             // 10: proto.Void
}
var file_submodule_protos_protos_private_proto_depIdxs = []int32{
	7,  // 0: proto.CreatePrivateReq.documentation:type_name -> proto.Documentation
	7,  // 1: proto.PrivateGet.documentation:type_name -> proto.Documentation
	3,  // 2: proto.UpdatePrivat.Body:type_name -> proto.BodyUpt
	7,  // 3: proto.BodyUpt.documentation:type_name -> proto.Documentation
	8,  // 4: proto.PrivateListReq.pagination:type_name -> proto.Pagination
	1,  // 5: proto.PrivateListRes.private:type_name -> proto.PrivateGet
	0,  // 6: proto.PrivateService.CreatePrivate:input_type -> proto.CreatePrivateReq
	9,  // 7: proto.PrivateService.GetPrivate:input_type -> proto.ById
	5,  // 8: proto.PrivateService.ListPrivates:input_type -> proto.PrivateListReq
	2,  // 9: proto.PrivateService.UpdatePrivate:input_type -> proto.UpdatePrivat
	4,  // 10: proto.PrivateService.DeletePrivate:input_type -> proto.DeletePrivat
	10, // 11: proto.PrivateService.CreatePrivate:output_type -> proto.Void
	1,  // 12: proto.PrivateService.GetPrivate:output_type -> proto.PrivateGet
	6,  // 13: proto.PrivateService.ListPrivates:output_type -> proto.PrivateListRes
	10, // 14: proto.PrivateService.UpdatePrivate:output_type -> proto.Void
	10, // 15: proto.PrivateService.DeletePrivate:output_type -> proto.Void
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_submodule_protos_protos_private_proto_init() }
func file_submodule_protos_protos_private_proto_init() {
	if File_submodule_protos_protos_private_proto != nil {
		return
	}
	file_submodule_protos_protos_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_submodule_protos_protos_private_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePrivateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PrivateGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePrivat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BodyUpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePrivat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PrivateListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_protos_protos_private_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PrivateListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_protos_protos_private_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_protos_protos_private_proto_goTypes,
		DependencyIndexes: file_submodule_protos_protos_private_proto_depIdxs,
		MessageInfos:      file_submodule_protos_protos_private_proto_msgTypes,
	}.Build()
	File_submodule_protos_protos_private_proto = out.File
	file_submodule_protos_protos_private_proto_rawDesc = nil
	file_submodule_protos_protos_private_proto_goTypes = nil
	file_submodule_protos_protos_private_proto_depIdxs = nil
}
